# Generated by Django 3.2 on 2021-04-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pdf_fast_v2',
            new_name='Pdf_fast_takaful',
        ),
    ]
