# Generated by Django 3.2 on 2021-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0002_rename_pdf_fast_v2_pdf_fast_takaful'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRI_PART_ENGAGEMENT_SECU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.CharField(max_length=9)),
                ('broker_cedant_name', models.CharField(max_length=50)),
                ('engagements', models.DecimalField(decimal_places=2, max_digits=28)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KRI_RISQUE_DEFAUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedant_code', models.CharField(max_length=9)),
                ('cedant_name', models.CharField(max_length=50)),
                ('risque_defaut', models.DecimalField(decimal_places=2, max_digits=28)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_ibnr', 'Acess the IBNR page'), ('vendor_rights', 'Global vendor rights'), ('any_rights', 'Global any rights')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
