# Generated by Django 3.2 on 2021-07-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0003_kri_part_engagement_secu_kri_risque_defaut_rightssupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_ibnr', 'Acess the IBNR page'), ('management', 'Acess the management page'), ('vendor_rights', 'Global vendor rights'), ('any_rights', 'Global any rights'))},
        ),
    ]
