# Generated by Django 3.2 on 2021-07-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0004_alter_rightssupport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_ibnr', 'Acess the IBNR page'), ('management', 'Acess the management page'), ('view_prov_egal_equi', 'Acess the PROV. EGAL-EQUI page'), ('vendor_rights', 'Global vendor rights'), ('any_rights', 'Global any rights'))},
        ),
    ]
