# Generated by Django 3.2 on 2021-08-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0010_segmentscna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentscna',
            name='is_total',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=1),
        ),
    ]
