# Generated by Django 3.2 on 2021-08-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0012_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
