# Generated by Django 3.2 on 2021-08-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0013_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmentscna',
            old_name='order',
            new_name='cna_order',
        ),
    ]
