# Generated by Django 3.2 on 2021-08-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0014_rename_order_segmentscna_cna_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cna_order', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
