# Generated by Django 3.2 on 2021-08-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0015_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
